name: debugger-action
on:
  workflow_dispatch: 
jobs:
  getinfo:
    runs-on: ubuntu-latest
    steps:
     - name: get
       run: |
        free -h
        lscpu
        df -h
        cat /etc/os-release
        lsb_release -a
